// react/src/ProtectedRoute.tsx
import React, { useEffect } from "react";
import { redirectToLogin } from "@aria-iam/core";
import { useAuth } from "./AuthProvider";

export const ProtectedRoute = ({ children }: { children: React.ReactNode }) => {
  const { status, appId, loginUrl } = useAuth();

  useEffect(() => {
    if (status === "unauthorized" || status === "unauthenticated") {
      redirectToLogin(loginUrl, appId);
    }
  }, [status, appId, loginUrl]);

  if (status === "checking") {
    return (
      <div className="w-full h-screen flex items-center justify-center text-xl font-sans">
        Carregando...
      </div>
    );
  }

  if (status === "unauthorized" || status === "unauthenticated") {
    return null;
  }

  return <>{children}</>;
};

// vue/src/components/ProtectedRoute.vue
<script setup lang="ts">
import { watch } from "vue";
import { redirectToLogin } from "@aria-iam/core";
import { useAuth } from "../composables/useAuth";
import { ariaState } from "../plugin";

const { status } = useAuth();

watch(
  status,
  (s) => {
    if (s !== "checking" && s !== "authorized") {
      redirectToLogin(ariaState.loginUrl, ariaState.appId);
    }
  },
  { immediate: true }
);
</script>

<template>
  <slot v-if="status === 'authorized'" />
</template>
